services:


  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: keycloak
    ports:
      - 5432:5432

    networks:
      - formation


networks:
  formation:
    # Use a custom driver
    external : true
